apiVersion: batch/v1
kind: Job
metadata:
  name: philipp-drl
  annotations:
    openshift.io/scc: maprkdf-scc
spec:
  parallelism: 10
  completions: 10
  template:
    metadata:
      name: philipp-drl
      annotations:
        openshift.io/scc: maprkdf-scc
    spec:
      containers:
      - name: philipp-drl
        image: docker-registry.default.svc:5000/appsdev/philipp-drl:latest
        command: ["python3",  "examples.py"]
        volumeMounts:
          - mountPath: "/output"
            name: liskov
      restartPolicy: Never # Not working in openshift
      volumes:
        - name: liskov
          persistentVolumeClaim:
            claimName: pvc-liskov-dpl
